openapi: 3.0.3
info:
  title: Marriage Allowance
  description: |-
    This API provides resources related to [Marriage Allowance](https://www.gov.uk/marriage-allowance).

    Marriage Allowance lets the lower earner of a couple transfer some of their Personal Allowance to their husband, wife or civil partner. If they are eligible this will then lower their tax bill.

    In particular, this API can

    * Retrieve an individual’s Marriage Allowance status
    * Check their partner’s eligibility to be a recipient of Marriage Allowance (useful if the individual is considering applying for Marriage Allowance)
    On 28 February 2020 version 1.0 will be switched off.

    Version 2.0 will be released on 23 October 2019 within the Sandbox and Production environment.
    The endpoint in this API is [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints). 
    Your users must grant authority for your software to access it by signing in to their HMRC online account.

    The API supports individual and agent users. Note that:
    - Individual users can only access their own information.
    - Agent users can only access their own clients’ data.

    The following options are supported for agents:

    **Option 1: Agent services account**

    If the agent uses an [agent services account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#agent-services-account),
    they can access their [existing 64-8 clients](https://www.gov.uk/guidance/client-authorisation-an-overview)
    who they have [linked to their agent services account](https://www.gov.uk/guidance/link-clients-to-your-agent-services-account#link-existing-clients)
    (restricted to 2 years’ history)

    **Option 2: HMRC online services for agents account**

    If the agent uses an [HMRC online services for agents account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#hmrc-online-services-for-agents-account)
    which is enrolled for [Self Assessment for Agents](https://www.gov.uk/guidance/self-assessment-for-agents-online-service),
    they will be able to access their [existing 64-8 clients](https://www.gov.uk/guidance/client-authorisation-an-overview)
    (restricted to 2 years’ history).
    When an API changes in a way that is backwards-incompatible, we increase the version number of the API. 
    See our [reference guide](/api-documentation/docs/reference-guide#versioning) for more on
    versioning.
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:
    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. 
    See our [reference guide](/api-documentation/docs/reference-guide#errors) for more on errors.
    You can use the sandbox environment to [test this API](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing).

    It supports [stateful behaviour](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing/stateful-behaviour). You can set up test data for this API using the [Marriage Allowance Test Support API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/marriage-allowance-des-stub).
  contact: {}
  version: '2.0'
servers:
  - url: https://api.service.hmrc.gov.uk/
    description: Production
    variables: {}
tags:
  - name: marriage-allowance
    description: ''
paths:
  /marriage-allowance/sa/{utr}/status:
    get:
      tags:
        - marriage-allowance
      summary: Get Marriage Allowance status
      description: |
        @*
         * Copyright 2022 HM Revenue & Customs
         *
         *@

        <p>This resource determines whether an individual taxpayer has Marriage Allowance for the given tax year. If they have Marriage Allowance it will return their role in the relationship (either 'Transferor' or 'Recipient').</p>
      operationId: GetMarriageAllowancestatus
      parameters:
        - name: utr
          in: path
          description: The 10 digit self-assessment UTR for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: '2234567890'
        - name: taxYear
          in: query
          description: The tax year for which the Marriage Allowance status is being retrieved, in the format YYYY-YY.
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: 2014-15
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: MarriageAllowanceSaStatusresponse
                    required: &ref_2
                      - status
                      - deceased
                    type: object
                    properties: &ref_3
                      status:
                        oneOf:
                          - title: Status
                            enum:
                              - Transferor
                            type: string
                            description: The taxpayer has transferred personal allowance in the given tax year
                          - title: Status1
                            enum:
                              - Recipient
                            type: string
                            description: The taxpayer has received personal allowance in the given tax year
                          - title: Status2
                            enum:
                              - None
                            type: string
                            description: The taxpayer has not transferred or received personal allowance in the given tax year
                        description: The role of the taxpayer as recipient or transferor.
                      deceased:
                        type: boolean
                        description: Whether the taxpayer is deceased or not.
                    description: Marriage Allowance status
                  - example:
                      status: Recipient
                      deceased: false
              examples:
                example-1:
                  value:
                    status: Recipient
                    deceased: false
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: errorResponse
                    required: &ref_0
                      - code
                    type: object
                    properties: &ref_1
                      code:
                        type: string
                  - example:
                      code: SA_UTR_INVALID
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingTaxYear:
                  description: Missing tax year
                  value:
                    code: TAX_YEAR_INVALID
        '401':
          description: Unauthorised
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: errorResponse
                    required: *ref_0
                    type: object
                    properties: *ref_1
                  - example:
                      code: UNAUTHORIZED
              examples:
                unauthorisedUser:
                  description: User not authorised
                  value:
                    code: UNAUTHORIZED
        '404':
          description: Not Found
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: errorResponse
                    required: *ref_0
                    type: object
                    properties: *ref_1
                  - example:
                      code: NOT_FOUND
              examples:
                unmatchedRecipient:
                  description: Unmatched recipient
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - User-Restricted:
            - read:marriage-allowance
  /marriage-allowance/sa/{utr}/eligibility:
    post:
      tags:
        - marriage-allowance
      summary: Check Marriage Allowance eligibility
      description: |
        @*
         * Copyright 2022 HM Revenue & Customs
         *
         *@

        <p> This resource checks whether an individual taxpayer's partner is eligible to become a recipient of Marriage
            Allowance for the given tax year.</p>

        <p>This resource should only be used when the individual is the lower earner and is considering becoming a
            transferor of Marriage Allowance. It should only be used to to check the eligibility of their own partner.</p>
      operationId: CheckMarriageAllowanceeligibility
      parameters:
        - name: utr
          in: path
          description: The 10 digit self-assessment UTR for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: '2234567890'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - title: MarriageAllowanceSaEligibilityrequest
                  required:
                    - nino
                    - firstname
                    - surname
                    - dateOfBirth
                    - taxYear
                  type: object
                  properties:
                    nino:
                      pattern: ^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))([A-Z]\s*){2})([0-9]\s*){6}([A-D]\s*)$
                      type: string
                      description: National Insurance number
                      example: AA000003D
                    firstname:
                      pattern: ^(.){1,35}$
                      type: string
                      description: Partner’s (potential recipient’s) first name
                      example: John
                    surname:
                      pattern: ^(.){1,35}$
                      type: string
                      description: Partner’s (potential recipient’s) surname
                      example: Wick
                    dateOfBirth:
                      pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
                      type: string
                      description: Partner’s (potential recipient’s) date of birth in YYYY-MM-DD format
                      example: '1987-12-20'
                    taxYear:
                      pattern: ^(19|20)[0-9]{2}-[1-9]{2}$
                      type: string
                      description: The tax year for which the Marriage Allowance eligibility is being retrieved, in the format YYYY-YY
                  description: Marriage Allowance eligibility
                - example:
                    nino: AA000003D
                    firstname: John
                    surname: Smith
                    dateOfBirth: '1981-01-31'
                    taxYear: 2018-19
            examples:
              example-1:
                value:
                  nino: AA000003D
                  firstname: John
                  surname: Smith
                  dateOfBirth: '1981-01-31'
                  taxYear: 2018-19
        required: true
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: MarriageAllowanceSaEligibilityresponse
                    required:
                      - eligible
                    type: object
                    properties:
                      eligible:
                        type: boolean
                        description: Whether the taxpayer's partner is eligible to become a recipient of Marriage Allowance.
                    description: Marriage Allowance eligibility
                  - example:
                      eligible: true
              examples:
                example-1:
                  value:
                    eligible: true
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: errorResponse
                    required: *ref_0
                    type: object
                    properties: *ref_1
                  - example:
                      code: SA_UTR_INVALID
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                missingNino:
                  description: Missing Nino
                  value:
                    code: BAD_REQUEST
                invalidNino:
                  description: Invalid NINO
                  value:
                    code: NINO_INVALID
                missingDateOfBirth:
                  description: Missing date of birth
                  value:
                    code: BAD_REQUEST
                invalidDateOfBirth:
                  description: Invalid date of birth
                  value:
                    code: DOB_INVALID
                missingTaxYear:
                  description: Missing tax year
                  value:
                    code: BAD_REQUEST
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingFirstName:
                  description: Missing first name
                  value:
                    code: BAD_REQUEST
                invalidFirstName:
                  description: Invalid first name
                  value:
                    code: FIRST_NAME_INVALID
                missingSurname:
                  description: Missing surname
                  value:
                    code: BAD_REQUEST
                invalidSurname:
                  description: Invalid surname
                  value:
                    code: SURNAME_VALID
        '401':
          description: Unathorised
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: errorResponse
                    required: *ref_0
                    type: object
                    properties: *ref_1
                  - example:
                      code: UNAUTHORIZED
              examples:
                unauthorisedUser:
                  description: User not authorised
                  value:
                    code: UNAUTHORIZED
        '404':
          description: Not Found
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - title: errorResponse
                    required: *ref_0
                    type: object
                    properties: *ref_1
                  - example:
                      code: NOT_FOUND
              examples:
                unmatchedRecipient:
                  description: Unmatched recipient
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - User-Restricted:
            - read:marriage-allowance
components:
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:marriage-allowance: Access Marriage Allowance
  schemas:
    MarriageAllowanceSaStatusresponse:
      title: MarriageAllowanceSaStatusresponse
      required: *ref_2
      type: object
      properties: *ref_3
      description: Marriage Allowance status
