openapi: 3.0.3
info:
  title: Marriage Allowance
  description: |
    # Authorisation

    The endpoints in this API are [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints).
    Your users must grant authority for your software to access them by signing in to their HMRC online account.

    The API supports individual and agent users. Note that:
    - Individual users can only access their own information.
    - Agent users can only access their own clients’ data.

    The following options are supported for agents:
      
    **Option 1: Agent services account**

    If the agent uses an [agent services account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#agent-services-account), they can access their [existing 64-8 clients](https://www.gov.uk/guidance/how-to-get-authorised-to-act-as-a-tax-agent-on-behalf-of-your-clients#get-authorised-using-online-services-online-forms-or-paper-forms) who they have linked to their agent services account (restricted to 2 years’ history).

    **Option 2: HMRC online services for agents account**
      
    If the agent uses an [HMRC online services for agents account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#hmrc-online-services-for-agents-account) which is enrolled for [Self Assessment for Agents](https://www.gov.uk/guidance/self-assessment-for-agents-online-service), they will be able to access their [existing 64-8 clients](https://www.gov.uk/guidance/how-to-get-authorised-to-act-as-a-tax-agent-on-behalf-of-your-clients#get-authorised-using-online-services-online-forms-or-paper-forms) (restricted to 2 years’ history).
  contact: {}
  version: '2.0'
servers:
  - url: https://api.service.hmrc.gov.uk
    description: Production
    variables: {}
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
    variables: {}
paths:
  /marriage-allowance/sa/{utr}/status:
    get:
      tags:
        - marriage-allowance
      summary: Get Marriage Allowance status
      description: This resource determines whether an individual taxpayer has Marriage Allowance for the given tax year. If they have Marriage Allowance it will return their role in the relationship (either 'Transferor' or 'Recipient').
      operationId: GetMarriageAllowancestatus
      parameters:
        - name: utr
          in: path
          description: The 10 digit self-assessment UTR for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: '2234567890'
        - name: taxYear
          in: query
          description: The tax year for which the Marriage Allowance status is being retrieved, in the format YYYY-YY.
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: 2014-15
      responses:
        '200':
          description: 'OK'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MarriageAllowanceSaStatusresponse'
              examples:
                example-1:
                  value:
                    status: Recipient
                    deceased: false
        '400':
          description: 'Bad Request'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingTaxYear:
                  description: Missing tax year
                  value:
                    code: TAX_YEAR_INVALID
        '401':
          description: 'Unauthorised'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unauthorisedUser:
                  description: User not authorised
                  value:
                    code: UNAUTHORIZED
        '404':
          description: 'Not Found'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unmatchedRecipient:
                  description: Unmatched recipient
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - User-Restricted:
            - read:marriage-allowance
  /marriage-allowance/sa/{utr}/eligibility:
    post:
      tags:
        - marriage-allowance
      summary: Check Marriage Allowance eligibility
      description: |
        This resource checks whether an individual taxpayer's partner is eligible to become a recipient of Marriage Allowance for the given tax year.

        This resource should only be used when the individual is the lower earner and is considering becoming a transferor of Marriage Allowance. It should only be used to to check the eligibility of their own partner.
      operationId: CheckMarriageAllowanceeligibility
      parameters:
        - name: utr
          in: path
          description: The 10 digit self-assessment UTR for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: '2234567890'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/MarriageAllowanceSaEligibilityrequest'
            examples:
              example-1:
                value:
                  nino: AA000003D
                  firstname: John
                  surname: Smith
                  dateOfBirth: 1981-01-31
                  taxYear: 2018-19
        required: true
      responses:
        '200':
          description: 'OK'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MarriageAllowanceSaEligibilityresponse'
              examples:
                example-1:
                  value:
                    eligible: true
        '400':
          description: 'Bad Request'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                missingNino:
                  description: Missing Nino
                  value:
                    code: BAD_REQUEST
                invalidNino:
                  description: Invalid NINO
                  value:
                    code: NINO_INVALID
                missingDateOfBirth:
                  description: Missing date of birth
                  value:
                    code: BAD_REQUEST
                invalidDateOfBirth:
                  description: Invalid date of birth
                  value:
                    code: DOB_INVALID
                missingTaxYear:
                  description: Missing tax year
                  value:
                    code: BAD_REQUEST
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingFirstName:
                  description: Missing first name
                  value:
                    code: BAD_REQUEST
                invalidFirstName:
                  description: Invalid first name
                  value:
                    code: FIRST_NAME_INVALID
                missingSurname:
                  description: Missing surname
                  value:
                    code: BAD_REQUEST
                invalidSurname:
                  description: Invalid surname
                  value:
                    code: SURNAME_VALID
        '401':
          description: 'Unathorised'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unauthorisedUser:
                  description: User not authorised
                  value:
                    code: UNAUTHORIZED
        '404':
          description: 'Not Found'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              examples:
                unmatchedRecipient:
                  description: Unmatched recipient
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - User-Restricted:
            - read:marriage-allowance
components:
  securitySchemes:
    User-Restricted:
      type:  oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:marriage-allowance: Access Marriage Allowance
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
    MarriageAllowanceSaEligibilityrequest:
      title: MarriageAllowanceSaEligibilityrequest
      required:
        - nino
        - firstname
        - surname
        - dateOfBirth
        - taxYear
      type: object
      properties:
        nino:
          pattern: ^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))([A-Z]\s*){2})([0-9]\s*){6}([A-D]\s*)$
          type: string
          description: National Insurance number
          example: AA000003D
        firstname:
          pattern: ^(.){1,35}$
          type: string
          description: Partner’s (potential recipient’s) first name
          example: John
        surname:
          pattern: ^(.){1,35}$
          type: string
          description: Partner’s (potential recipient’s) surname
          example: Wick
        dateOfBirth:
          pattern: ^(19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$
          type: string
          description: Partner’s (potential recipient’s) date of birth in YYYY-MM-DD format
          example: 1987-12-20
        taxYear:
          pattern: ^(19|20)[0-9]{2}-[1-9]{2}$
          type: string
          description: The tax year for which the Marriage Allowance eligibility is being retrieved, in the format YYYY-YY
      description: Marriage Allowance eligibility
    MarriageAllowanceSaEligibilityresponse:
      title: MarriageAllowanceSaEligibilityresponse
      required:
        - eligible
      type: object
      properties:
        eligible:
          type: boolean
          description: Whether the taxpayer's partner is eligible to become a recipient of Marriage Allowance.
      description: Marriage Allowance eligibility
    MarriageAllowanceSaStatusresponse:
      title: MarriageAllowanceSaStatusresponse
      required:
        - status
        - deceased
      type: object
      properties:
        status:
          oneOf:
            - $ref: '#/components/schemas/Status'
            - $ref: '#/components/schemas/Status1'
            - $ref: '#/components/schemas/Status2'
          description: The role of the taxpayer as recipient or transferor.
        deceased:
          type: boolean
          description: Whether the taxpayer is deceased or not.
      description: Marriage Allowance status
    Status:
      title: Status
      enum:
        - Transferor
      type: string
      description: The taxpayer has transferred personal allowance in the given tax year
    Status1:
      title: Status1
      enum:
        - Recipient
      type: string
      description: The taxpayer has received personal allowance in the given tax year
    Status2:
      title: Status2
      enum:
        - None
      type: string
      description: The taxpayer has not transferred or received personal allowance in the given tax year
tags:
  - name: marriage-allowance
    description: ''
